### ISSUE TITLE
composer update dosn't work

### ISSUE THREAD

**Issue by danielczestki** [lukefor/Laravel4-SmartyView#11]
I get:
Downloading: connection...Failed to download dark/smarty-view from dist: The "https://api.github.com/repos/darkimmortal/Laravel4-SmartyView/zipball/cd7f7ac123b2f8fa9f36f78c464c3432ec08a0b3" file could not be down
loaded (HTTP/1.1 404 Not Found)

"dev-laravel-4.2"

**Comment by lukefor** [comment]
I've contacted packagist about this, seems the download URL didn't update when I changed my github username and I can't get it to change manually

**Comment by lukefor** [comment]
All sorted now
